name: Deploy to Raspberry Pi
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = aarch64-linux
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Install and Connect WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools openresolv

          echo "${{ secrets.WG_CONF }}" | sudo tee /etc/wireguard/wg0.conf > /dev/null

          sudo chmod 600 /etc/wireguard/wg0.conf
          sudo wg-quick up wg0
          sudo wg show

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519

          ssh-keyscan -H 192.168.68.80 >> ~/.ssh/known_hosts

      - name: NixOS Rebuild & Switch
        env:
          NIX_SSHOPTS: "-o StrictHostKeyChecking=no"
        run: |
          nixos-rebuild switch \
            --flake .#rui-nixos-pi \
            --target-host rui@192.168.68.80 \
            --use-remote-sudo \
            --show-trace
