name: Deploy to Host
on:
  workflow_dispatch:
    inputs:
      target_host:
        description: "Target Host (Flake Output)"
        required: true
        type: choice
        default: vm-app
        options:
          - pi
          - vm-app
          - vm-monitor
          - vm-network
      runner_os:
        description: "Runner OS"
        required: true
        type: choice
        default: "ubuntu-latest"
        options:
          - "ubuntu-latest"
          - "ubuntu-24.04-arm"

jobs:
  deploy:
    runs-on: ${{ inputs.runner_os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Host IP Address
        id: config
        run: |
          case "${{ inputs.target_host }}" in
            "pi")
              echo "TARGET_IP=192.168.20.51" >> $GITHUB_ENV
              ;;
            "vm-app")
              echo "TARGET_IP=192.168.20.2" >> $GITHUB_ENV
              ;;
            "vm-monitor")
              echo "TARGET_IP=192.168.20.3" >> $GITHUB_ENV
              ;;
            "vm-network")
              echo "TARGET_IP=192.168.20.1" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown host selected"
              exit 1
              ;;
          esac

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Install and Connect WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard-tools
          echo "${{ secrets.WG_CONF }}" | sudo tee /etc/wireguard/wg0.conf > /dev/null
          sudo chmod 600 /etc/wireguard/wg0.conf
          sudo wg-quick up wg0
          sudo wg show

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ env.TARGET_IP }} >> ~/.ssh/known_hosts

      - name: NixOS Rebuild & Switch
        env:
          NIX_SSHOPTS: "-o StrictHostKeyChecking=no"
        run: |
          nix run github:nixos/nixpkgs/nixos-unstable#nixos-rebuild -- switch \
            --flake .#${{ inputs.target_host }} \
            --target-host root@${{ env.TARGET_IP }} \
            --show-trace
